version: 2

jobs:
  test:
    machine: true
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: export TERM=xterm && gradle dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      - run:
          name: Run all tests
          command: gradle test

  deploy:
    machine: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - "96:2c:54:e3:52:7c:c8:89:e3:0f:58:44:d8:be:71:fb"
      - run:
          name: Update docker-compose
          command: ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -t root@ampnet.io "docker-compose pull -f /home/eugen/ampnet-docker-compose/docker-compose.yml"
      - run:
          name: Run docker-compose
          command: ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -t root@ampnet.io "docker-compose up -f /home/eugen/ampnet-docker-compose/docker-compose.yml"

workflows:
  version: 2

  test-deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master

  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - test
