version: 2
executorType: machine
jobs:
  test:
    machine: true
    environment:
      TERM: dumb
    working_directory: ~/repo

    steps:
      - checkout
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - run: docker network prune -f

      - restore_cache:
          keys:
            - v1-dep-{{ .Branch }}-
            - v1-dep-master-
            - v1-dep-

      - run: sudo chmod +x ./gradlew
      - run: ./gradlew dependencies

      - save_cache:
          key: v1-dep-{{ .Branch }}-{{ epoch }}
          paths:
            - vendor/bundle
            - ~/virtualenvs
            - ~/.m2
            - ~/.ivy2
            - ~/.bundle
            - ~/.go_workspace
            - ~/.gradle
            - ~/.cache/bower

      - run: ./gradlew test

  deploy:
    machine: true
    environment:
      TERM: dumb
    steps:
      - add_ssh_keys:
          fingerprints:
            - "96:2c:54:e3:52:7c:c8:89:e3:0f:58:44:d8:be:71:fb"
      - run:
          name: Update docker-compose
          command: ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -t root@ampnet.io "docker-compose -f /home/eugen/ampnet-docker-compose/docker-compose.yml pull --ignore-pull-failures"
      - run:
          name: Run docker-compose
          command: ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -t root@ampnet.io "docker-compose -f /home/eugen/ampnet-docker-compose/docker-compose.yml up -d"

workflows:
  version: 2

  test-deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master

  nightly:
    triggers:
      - schedule:
          cron: "0 4 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - test
